feat/suggestions enhancement
appbaseio/vue-playground pull request #72
Opened 2023-08-23 08:25 UTC by SavvyShah

[Main PR](https://github.com/appbaseio/reactivesearch/pull/2242)

2023-09-04 04:57 UTC, mohdashraf010897 requested changes
Please refer to the review comments

2023-09-04 04:57 UTC, mohdashraf010897 commented on stories/SearchBoxWithDocumentSuggestions.vue
@SavvyShah I believe we could just utilize one file for all type of document suggestions stories.
One recommendation is to use internal props to conditionally leverage slots, refer here - https://github.com/appbaseio/vue-playground/pull/70/files#r1314435927

2023-09-04 04:57 UTC, mohdashraf010897 commented on stories/index.stories.js
> +	.add('with showDistinctSuggestions', () => ({
@SavvyShah The order of the stories should be maintained, let's have all the document suggestions stories right after the last added story, which in this case is the [compoundClause story](https://github.com/appbaseio/vue-playground/blob/75de207395a6a51e763d4c8dff022887cbd50e53/stories/index.stories.js#L1239).

2023-09-05 06:07 UTC, SavvyShah commented on stories/SearchBoxWithDocumentSuggestions.vue
OK. This is useful. We can conditionally render the `#renderItem` slot. Correct?

2023-09-15 15:22 UTC, merged